# Generated by Django 5.2.1 on 2025-05-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('post_on', models.DateTimeField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/image/')),
                ('content', models.TextField(max_length=5000)),
            ],
        ),
    ]
