# Generated by Django 5.2.1 on 2025-05-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_header', models.CharField(max_length=20)),
                ('blog_author', models.CharField(max_length=15)),
                ('blog_creatat', models.DateTimeField(auto_now_add=True)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('blog_content', models.TextField(max_length=3000)),
            ],
        ),
    ]
