# Generated by Django 5.2.1 on 2025-05-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_all',
            name='blog_header',
            field=models.CharField(max_length=150),
        ),
    ]
