# Generated by Django 5.2.1 on 2025-05-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_blog_all_blog_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_header', models.CharField(max_length=150)),
                ('intro_createdat', models.DateTimeField(auto_now_add=True)),
                ('intro_image', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('intro_content', models.TextField(max_length=3000)),
            ],
        ),
    ]
